apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiMDRkZWVwYWsiLCJwYXNzd29yZCI6ImdocF83VGxNNGtoOVkxRE9iVnY3ekFxUFkyN0xyUzF4eWYzUWM0M3MiLCJlbWFpbCI6ImRlZXBha2JoYXJhdGU1NDMyMUBnbWFpbC5jb20iLCJhdXRoIjoiTURSa1pXVndZV3M2WjJod1h6ZFViRTAwYTJnNVdURkVUMkpXZGpkNlFYRlFXVEkzVEhKVE1YaDVaak5SWXpRemN3PT0ifX19
kind: Secret
metadata:
  name: ghcr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
