# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: todo-frontend-app
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-options: CreateNamespace=true
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/04Deepak/todo-gitops.git   # Replace it with your forked repo
#     targetRevision: main
#     path: applications/todo_frontend
#   destination:
#     server: https://kubernetes.default.svc   # Replace with your Cluster Url, To get run: `argocd cluster list`
#     namespace: deafult
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true

    

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/04Deepak/todo-gitops.git    # Replace it with your forked repo
    targetRevision: main
    path: applications/todo_frontend
  destination:
    server: https://kubernetes.default.svc   # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    

