apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
spec:
  selector:
    app: todo-frontend
  ports:
  - port: 80

    targetPort: 80


# apiVersion: v1
# kind: Service
# metadata:
#   name: todo-frontend-svc
#   namespace: default
# spec:
#   type: ClusterIP
#   selector:
#     app: todo-frontend
#   ports:
#     - port: 80
#       targetPort: 80

