apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/04Deepak/todo-frontend.git    # Replace it with your forked repo
    targetRevision: main
    path: applications/todo_frontend
  destination:
    server: https://172.31.6.84:33893   # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    