apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secrets
type: Opaque
stringData:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9zZGVlcGFrMTUyMV9kYl91c2VyOjFtd3RxTGpCaU84cFRBT0VAY2x1c3RlcjAucXF6dXV0cy5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA=="
  JWT_SECRET: "dGFza21hc3Rlcl9zdXBlcl9zZWNyZXRfand0X2tleV8yMDI0X3NlY3VyZV9yYW5kb21fc3RyaW5nX3h5ejc4OQ=="
